name: ui_widgets
description: "A Flutter package for efficient UI state management, handling loading, empty views, content display, caching, and pull-to-refresh with customizable widgets."
version: 0.0.1
homepage: https://github.com/abdelrahmanghanem
repository: https://github.com/abdelrahmanghanem/ui_widgets

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

